- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  community.kubernetes.helm:
    name: welltory
    chart_ref: stable/prometheus
    release_namespace: monitoring
    create_namespace: true
      values:
        server.retentionTime: {{ Prometheus_retention_days }}
        image.tag: {{ Prometheus_version }}
