- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  community.kubernetes.helm:
    name: welltory-prometheus
    chart_ref: stable/prometheus
    release_namespace: monitoring
    create_namespace: true
      values:
        server.retentionTime: {{ Prometheus_retention_days }}
        image.tag: {{ Prometheus_version }}
        
- name: Enabling RBAC for Prometheus
  community.kubernetes.k8s:
    state: present
    template: '/templates/prometheus-rbac.yml.j2'
